pipeline {
    agent {
      label 'jenkins-agent-cypress'
    }

    stages {
        stage ('Install Dependencies') {
            steps {
              sh """
                cd scoreboard
                npm install
              """
            }
        }
        stage ('Build') {
            steps {
              sh """
                cd scoreboard
                npm run build
              """
            }
        }
        stage ('Unit Tests') {
            steps {
                sh """
                  cd scoreboard
                  CI=true npm test
                """
            }
        }
        stage ('Functional Tests') {
            steps {
                sh """
                  cd scoreboard
                  npm run cy:ci
                """
            }
        }
    }
}
