pipeline {
    agent {
      label 'jenkins-agent-npm'
    }

    stages {
        stage ('Install Dependencies') {
            steps {
              sh """
                cd scoreboard
                npm install
              """
            }
        }
    }
}
