pipeline {
    agent {
        node {
            label 'master'
        }
    }

    stages {
        stage('Check Style') {
            steps {
                dir("greeting-service") {
                    sh 'ls -l'
                    sh './mvnw checkstyle:check'
                }
            }
        }

        stage('Test') {
            steps {
                dir("greeting-service") {
                    sh './mvnw test'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    oc project rht-jramirez-test-app
                    oc new-app --name greeting-service https://github.com/RedHatTraining/DO400-apps \
                        --context-dir greeting-servcie

                    oc expose svc/greeting-service
                '''
            }
        }
    }

}