pipeline {
    agent {
        node {
            label 'master'
        }
    }

    stages {
        stage('Check Style') {
            steps {
                sh 'ls -l'
                sh './mvnw checkstyle:check'
            }
        }

        stage('Test') {
            steps {
                sh './mvnw test'
            }
        }
    }

}